name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Aftman
              uses: ok-nick/setup-aftman@v0

            - name: Authenticate Wally
              run: wally login --token ${{ secrets.WALLY_ACCESS_TOKEN }}

            - name: Publish to Wally
              run: wally publish

            - name: Build project
              run: rojo build --output Signal.rbxm

            - name: Create GitHub Release
              id: create_release
              uses: ncipollo/release-action@v1
              with:
                artifacts: ./Signal.rbxm
                draft: true

            - name: Set git author information
              run: | 
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config user.name "github-actions[bot]"
                |

            - name: Deploy docs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - run: npx moonwave build --publish