name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Aftman
              uses: ok-nick/setup-aftman@v0

            - name: Authenticate Wally
              run: wally login --token ${{ secrets.WALLY_ACCESS_TOKEN }}

            - name: Publish to Wally
              run: wally publish

            - name: Build project
              run: rojo build --output Signal.rbxm

            - name: Create GitHub Release
              id: create_release
              uses: ncipollo/release-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                name: Release ${{ github.ref }}
                tag: ${{ github.ref }}
                draft: true

            - name: Upload build artifact
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./Signal.rbxm
                asset_name: Signal.rbxm
                asset_content_type: application/octet-stream
