name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Aftman
              uses: ok-nick/setup-aftman@v0

            - name: Authenticate Wally
              run: wally login --token ${{ secrets.WALLY_ACCESS_TOKEN }}

            - name: Publish to Wally
              run: wally publish

            - name: Build project
              run: rojo build --output Signal.rbxm

            - name: Create GitHub Release
              id: create_release
              uses: ncipollo/release-action@v1
              with:
                artifacts: ./Signal.rbxm
                draft: true

            - name: Set up node
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Deploy docs
              run: |
                git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                git config --global user.email "support+actions@github.com"
                git config --global user.name "github-actions-bot"
                npx moonwave build --publish --code src
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}