name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Aftman
              uses: ok-nick/setup-aftman@v0

            - name: Authenticate Wally
              run: wally login --token ${{ secrets.WALLY_ACCESS_TOKEN }}

            - name: Publish to Wally
              run: wally publish

            - name: Build project
              run: rojo build --output Signal.rbxm

            - name: Create GitHub Release
              id: create_release
              uses: ncipollo/release-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                artifacts: ./Signal.rbxm
                draft: true